ci pipeline added

diff --git a/.github/workflows/smartspend.yml b/.github/workflows/smartspend.yml
--- a/.github/workflows/smartspend.yml
+++ b/.github/workflows/smartspend.yml
@@ -20,10 +20,21 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Build with maven
-        run: mvn clean package
+      - name: Build with Maven
+        run: mvn clean package -Dspring.profiles.active=ci
 
-      - name : Login to Docker
+      - name: Check Docker secrets
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "DOCKERHUB_USERNAME is missing"
+            exit 1
+          fi
+          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+            echo "DOCKERHUB_TOKEN is missing"
+            exit 1
+          fi
+
+      - name: Login to Docker
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
@@ -34,4 +45,3 @@ jobs:
 
       - name: Push to Docker
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/smartspend-backend:latest
-
